/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Generate threshold key shares using Shamir's Secret Sharing
 *
 * # Arguments
 * * `threshold` - Minimum shares needed to reconstruct (e.g., 2)
 * * `total_parties` - Total number of shares (e.g., 3)
 *
 * # Returns
 * Vector of key shares, one for each party
 */
export declare function generateThresholdKeysSimple(threshold: number, totalParties: number): Array<Buffer>
/**
 * Reconstruct private key from threshold shares and sign
 *
 * # Arguments
 * * `shares` - At least `threshold` key shares
 * * `message_hash` - Message hash to sign (32 bytes)
 *
 * # Returns
 * ECDSA signature (64 bytes: r + s)
 */
export declare function thresholdSignSimple(shares: Array<Buffer>, messageHash: Buffer): Buffer
/**
 * Split an EXISTING private key into Shamir 2-of-3 shares
 *
 * Used for importing existing wallets (e.g., from MetaMask) into Ritkey.
 *
 * # Arguments
 * * `private_key` - 32-byte private key (hex without 0x prefix or with)
 * * `threshold` - Minimum shares needed to reconstruct (e.g., 2)
 * * `total_parties` - Total number of shares (e.g., 3)
 *
 * # Returns
 * Vector of key shares, one for each party
 */
export declare function splitExistingKey(privateKey: Buffer, threshold: number, totalParties: number): Array<Buffer>
/**
 * Reconstruct private key from threshold shares (for export)
 *
 * WARNING: This exposes the private key in memory.
 * Used for exporting wallets to external apps (MetaMask, Rabby, etc.)
 *
 * # Arguments
 * * `shares` - At least `threshold` key shares
 *
 * # Returns
 * 32-byte private key
 */
export declare function reconstructPrivateKey(shares: Array<Buffer>): Buffer
/**
 * Encrypt data with AES-256-GCM
 *
 * # Arguments
 * * `plaintext` - Data to encrypt
 * * `key` - 32-byte encryption key
 *
 * # Returns
 * Encrypted data (nonce + ciphertext + tag)
 */
export declare function encryptAesGcm(plaintext: Buffer, key: Buffer): Buffer
/**
 * Decrypt data with AES-256-GCM
 *
 * # Arguments
 * * `ciphertext` - Encrypted data (nonce + ciphertext + tag)
 * * `key` - 32-byte encryption key
 *
 * # Returns
 * Decrypted plaintext
 */
export declare function decryptAesGcm(ciphertext: Buffer, key: Buffer): Buffer
/** Generate random encryption key (32 bytes) */
export declare function generateEncryptionKey(): Buffer
/**
 * Sign message with ECDSA (secp256k1)
 *
 * # Arguments
 * * `message` - Message to sign (will be hashed with SHA256)
 * * `private_key` - 32-byte private key
 *
 * # Returns
 * 65-byte signature (r + s + v)
 */
export declare function signEcdsa(message: Buffer, privateKey: Buffer): Buffer
/**
 * Verify ECDSA signature
 *
 * # Arguments
 * * `message` - Original message
 * * `signature` - 65-byte signature
 * * `public_key` - 33 or 65 byte public key
 *
 * # Returns
 * true if signature is valid
 */
export declare function verifyEcdsa(message: Buffer, signature: Buffer, publicKey: Buffer): boolean
/**
 * Generate secp256k1 keypair
 *
 * # Returns
 * (private_key, public_key)
 */
export declare function generateKeypair(): Array<Buffer>
/** Derive public key from private key */
export declare function derivePublicKey(privateKey: Buffer): Buffer
/** Initialize the crypto module */
export declare function init(): string
/** Get module version */
export declare function version(): string
